// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Angry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Angry_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Angry_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Angry_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Angry_2eproto {
  static const ::uint32_t offsets[];
};
class Angry_proto;
struct Angry_protoDefaultTypeInternal;
extern Angry_protoDefaultTypeInternal _Angry_proto_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Angry_proto final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Angry_proto) */ {
 public:
  inline Angry_proto() : Angry_proto(nullptr) {}
  ~Angry_proto() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Angry_proto(::google::protobuf::internal::ConstantInitialized);

  Angry_proto(const Angry_proto& from);
  Angry_proto(Angry_proto&& from) noexcept
    : Angry_proto() {
    *this = ::std::move(from);
  }

  inline Angry_proto& operator=(const Angry_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline Angry_proto& operator=(Angry_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Angry_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const Angry_proto* internal_default_instance() {
    return reinterpret_cast<const Angry_proto*>(
               &_Angry_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Angry_proto& a, Angry_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(Angry_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Angry_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Angry_proto* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Angry_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)  final;
  void CopyFrom(const Angry_proto& from);
  void MergeFrom(const Angry_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Angry_proto* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Angry_proto";
  }
  protected:
  explicit Angry_proto(::google::protobuf::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // repeated sint32 data = 1;
  int data_size() const;
  private:
  int _internal_data_size() const;

  public:
  void clear_data() ;
  ::int32_t data(int index) const;
  void set_data(int index, ::int32_t value);
  void add_data(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& data() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_data();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_data() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_data();

  public:
  // optional float value = 2;
  bool has_value() const;
  void clear_value() ;
  float value() const;
  void set_value(float value);

  private:
  float _internal_value() const;
  void _internal_set_value(float value);

  public:
  // @@protoc_insertion_point(class_scope:Angry_proto)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> data_;
    mutable ::google::protobuf::internal::CachedSize _data_cached_byte_size_;
    float value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Angry_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Angry_proto

// repeated sint32 data = 1;
inline int Angry_proto::_internal_data_size() const {
  return _internal_data().size();
}
inline int Angry_proto::data_size() const {
  return _internal_data_size();
}
inline void Angry_proto::clear_data() {
  _internal_mutable_data()->Clear();
}
inline ::int32_t Angry_proto::data(int index) const {
  // @@protoc_insertion_point(field_get:Angry_proto.data)
  return _internal_data().Get(index);
}
inline void Angry_proto::set_data(int index, ::int32_t value) {
  _internal_mutable_data()->Set(index, value);
  // @@protoc_insertion_point(field_set:Angry_proto.data)
}
inline void Angry_proto::add_data(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_data()->Add(value);
  // @@protoc_insertion_point(field_add:Angry_proto.data)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& Angry_proto::data() const {
  // @@protoc_insertion_point(field_list:Angry_proto.data)
  return _internal_data();
}
inline ::google::protobuf::RepeatedField<::int32_t>* Angry_proto::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:Angry_proto.data)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_data();
}

inline const ::google::protobuf::RepeatedField<::int32_t>& Angry_proto::_internal_data() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.data_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* Angry_proto::_internal_mutable_data() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.data_;
}

// optional float value = 2;
inline bool Angry_proto::has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Angry_proto::clear_value() {
  _impl_.value_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float Angry_proto::value() const {
  // @@protoc_insertion_point(field_get:Angry_proto.value)
  return _internal_value();
}
inline void Angry_proto::set_value(float value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:Angry_proto.value)
}
inline float Angry_proto::_internal_value() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.value_;
}
inline void Angry_proto::_internal_set_value(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.value_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Angry_2eproto_2epb_2eh
