// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dog.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Dog_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Dog_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Dog_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Dog_2eproto {
  static const ::uint32_t offsets[];
};
class Dog_proto;
struct Dog_protoDefaultTypeInternal;
extern Dog_protoDefaultTypeInternal _Dog_proto_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Dog_proto final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Dog_proto) */ {
 public:
  inline Dog_proto() : Dog_proto(nullptr) {}
  ~Dog_proto() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Dog_proto(::google::protobuf::internal::ConstantInitialized);

  Dog_proto(const Dog_proto& from);
  Dog_proto(Dog_proto&& from) noexcept
    : Dog_proto() {
    *this = ::std::move(from);
  }

  inline Dog_proto& operator=(const Dog_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline Dog_proto& operator=(Dog_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Dog_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const Dog_proto* internal_default_instance() {
    return reinterpret_cast<const Dog_proto*>(
               &_Dog_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Dog_proto& a, Dog_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(Dog_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Dog_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Dog_proto* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Dog_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)  final;
  void CopyFrom(const Dog_proto& from);
  void MergeFrom(const Dog_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Dog_proto* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Dog_proto";
  }
  protected:
  explicit Dog_proto(::google::protobuf::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAFieldNumber = 1,
    kBFieldNumber = 2,
    kCFieldNumber = 3,
    kXFieldNumber = 4,
    kYFieldNumber = 5,
    kZFieldNumber = 6,
  };
  // optional float a = 1;
  bool has_a() const;
  void clear_a() ;
  float a() const;
  void set_a(float value);

  private:
  float _internal_a() const;
  void _internal_set_a(float value);

  public:
  // optional float b = 2;
  bool has_b() const;
  void clear_b() ;
  float b() const;
  void set_b(float value);

  private:
  float _internal_b() const;
  void _internal_set_b(float value);

  public:
  // optional float c = 3;
  bool has_c() const;
  void clear_c() ;
  float c() const;
  void set_c(float value);

  private:
  float _internal_c() const;
  void _internal_set_c(float value);

  public:
  // optional float x = 4;
  bool has_x() const;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // optional float y = 5;
  bool has_y() const;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // optional float z = 6;
  bool has_z() const;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:Dog_proto)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    float a_;
    float b_;
    float c_;
    float x_;
    float y_;
    float z_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Dog_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Dog_proto

// optional float a = 1;
inline bool Dog_proto::has_a() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Dog_proto::clear_a() {
  _impl_.a_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float Dog_proto::a() const {
  // @@protoc_insertion_point(field_get:Dog_proto.a)
  return _internal_a();
}
inline void Dog_proto::set_a(float value) {
  _internal_set_a(value);
  // @@protoc_insertion_point(field_set:Dog_proto.a)
}
inline float Dog_proto::_internal_a() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.a_;
}
inline void Dog_proto::_internal_set_a(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.a_ = value;
}

// optional float b = 2;
inline bool Dog_proto::has_b() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Dog_proto::clear_b() {
  _impl_.b_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float Dog_proto::b() const {
  // @@protoc_insertion_point(field_get:Dog_proto.b)
  return _internal_b();
}
inline void Dog_proto::set_b(float value) {
  _internal_set_b(value);
  // @@protoc_insertion_point(field_set:Dog_proto.b)
}
inline float Dog_proto::_internal_b() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.b_;
}
inline void Dog_proto::_internal_set_b(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.b_ = value;
}

// optional float c = 3;
inline bool Dog_proto::has_c() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Dog_proto::clear_c() {
  _impl_.c_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float Dog_proto::c() const {
  // @@protoc_insertion_point(field_get:Dog_proto.c)
  return _internal_c();
}
inline void Dog_proto::set_c(float value) {
  _internal_set_c(value);
  // @@protoc_insertion_point(field_set:Dog_proto.c)
}
inline float Dog_proto::_internal_c() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.c_;
}
inline void Dog_proto::_internal_set_c(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.c_ = value;
}

// optional float x = 4;
inline bool Dog_proto::has_x() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Dog_proto::clear_x() {
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float Dog_proto::x() const {
  // @@protoc_insertion_point(field_get:Dog_proto.x)
  return _internal_x();
}
inline void Dog_proto::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Dog_proto.x)
}
inline float Dog_proto::_internal_x() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.x_;
}
inline void Dog_proto::_internal_set_x(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.x_ = value;
}

// optional float y = 5;
inline bool Dog_proto::has_y() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Dog_proto::clear_y() {
  _impl_.y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline float Dog_proto::y() const {
  // @@protoc_insertion_point(field_get:Dog_proto.y)
  return _internal_y();
}
inline void Dog_proto::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Dog_proto.y)
}
inline float Dog_proto::_internal_y() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.y_;
}
inline void Dog_proto::_internal_set_y(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.y_ = value;
}

// optional float z = 6;
inline bool Dog_proto::has_z() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void Dog_proto::clear_z() {
  _impl_.z_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline float Dog_proto::z() const {
  // @@protoc_insertion_point(field_get:Dog_proto.z)
  return _internal_z();
}
inline void Dog_proto::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Dog_proto.z)
}
inline float Dog_proto::_internal_z() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.z_;
}
inline void Dog_proto::_internal_set_z(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.z_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Dog_2eproto_2epb_2eh
