// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameObject.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_GameObject_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_GameObject_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "Vect.pb.h"
#include "Matrix.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_GameObject_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_GameObject_2eproto {
  static const ::uint32_t offsets[];
};
class GameObject_proto;
struct GameObject_protoDefaultTypeInternal;
extern GameObject_protoDefaultTypeInternal _GameObject_proto_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class GameObject_proto final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:GameObject_proto) */ {
 public:
  inline GameObject_proto() : GameObject_proto(nullptr) {}
  ~GameObject_proto() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR GameObject_proto(::google::protobuf::internal::ConstantInitialized);

  GameObject_proto(const GameObject_proto& from);
  GameObject_proto(GameObject_proto&& from) noexcept
    : GameObject_proto() {
    *this = ::std::move(from);
  }

  inline GameObject_proto& operator=(const GameObject_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameObject_proto& operator=(GameObject_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const GameObject_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameObject_proto* internal_default_instance() {
    return reinterpret_cast<const GameObject_proto*>(
               &_GameObject_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GameObject_proto& a, GameObject_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(GameObject_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameObject_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameObject_proto* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameObject_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)  final;
  void CopyFrom(const GameObject_proto& from);
  void MergeFrom(const GameObject_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GameObject_proto* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "GameObject_proto";
  }
  protected:
  explicit GameObject_proto(::google::protobuf::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPoMatrixFieldNumber = 1,
    kPoVectFieldNumber = 2,
    kVAFieldNumber = 5,
    kXFieldNumber = 3,
    kIFieldNumber = 4,
  };
  // optional .Matrix_proto poMatrix = 1;
  bool has_pomatrix() const;
  void clear_pomatrix() ;
  const ::Matrix_proto& pomatrix() const;
  PROTOBUF_NODISCARD ::Matrix_proto* release_pomatrix();
  ::Matrix_proto* mutable_pomatrix();
  void set_allocated_pomatrix(::Matrix_proto* value);
  void unsafe_arena_set_allocated_pomatrix(::Matrix_proto* value);
  ::Matrix_proto* unsafe_arena_release_pomatrix();

  private:
  const ::Matrix_proto& _internal_pomatrix() const;
  ::Matrix_proto* _internal_mutable_pomatrix();

  public:
  // optional .Vect_proto poVect = 2;
  bool has_povect() const;
  void clear_povect() ;
  const ::Vect_proto& povect() const;
  PROTOBUF_NODISCARD ::Vect_proto* release_povect();
  ::Vect_proto* mutable_povect();
  void set_allocated_povect(::Vect_proto* value);
  void unsafe_arena_set_allocated_povect(::Vect_proto* value);
  ::Vect_proto* unsafe_arena_release_povect();

  private:
  const ::Vect_proto& _internal_povect() const;
  ::Vect_proto* _internal_mutable_povect();

  public:
  // optional .Vect_proto vA = 5;
  bool has_va() const;
  void clear_va() ;
  const ::Vect_proto& va() const;
  PROTOBUF_NODISCARD ::Vect_proto* release_va();
  ::Vect_proto* mutable_va();
  void set_allocated_va(::Vect_proto* value);
  void unsafe_arena_set_allocated_va(::Vect_proto* value);
  ::Vect_proto* unsafe_arena_release_va();

  private:
  const ::Vect_proto& _internal_va() const;
  ::Vect_proto* _internal_mutable_va();

  public:
  // optional float x = 3;
  bool has_x() const;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // optional sint32 i = 4;
  bool has_i() const;
  void clear_i() ;
  ::int32_t i() const;
  void set_i(::int32_t value);

  private:
  ::int32_t _internal_i() const;
  void _internal_set_i(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GameObject_proto)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5, 3, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::Matrix_proto* pomatrix_;
    ::Vect_proto* povect_;
    ::Vect_proto* va_;
    float x_;
    ::int32_t i_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameObject_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GameObject_proto

// optional .Matrix_proto poMatrix = 1;
inline bool GameObject_proto::has_pomatrix() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.pomatrix_ != nullptr);
  return value;
}
inline const ::Matrix_proto& GameObject_proto::_internal_pomatrix() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::Matrix_proto* p = _impl_.pomatrix_;
  return p != nullptr ? *p : reinterpret_cast<const ::Matrix_proto&>(::_Matrix_proto_default_instance_);
}
inline const ::Matrix_proto& GameObject_proto::pomatrix() const {
  // @@protoc_insertion_point(field_get:GameObject_proto.poMatrix)
  return _internal_pomatrix();
}
inline void GameObject_proto::unsafe_arena_set_allocated_pomatrix(::Matrix_proto* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pomatrix_);
  }
  _impl_.pomatrix_ = reinterpret_cast<::Matrix_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameObject_proto.poMatrix)
}
inline ::Matrix_proto* GameObject_proto::release_pomatrix() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Matrix_proto* released = _impl_.pomatrix_;
  _impl_.pomatrix_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Matrix_proto* GameObject_proto::unsafe_arena_release_pomatrix() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:GameObject_proto.poMatrix)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Matrix_proto* temp = _impl_.pomatrix_;
  _impl_.pomatrix_ = nullptr;
  return temp;
}
inline ::Matrix_proto* GameObject_proto::_internal_mutable_pomatrix() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.pomatrix_ == nullptr) {
    auto* p = CreateMaybeMessage<::Matrix_proto>(GetArenaForAllocation());
    _impl_.pomatrix_ = reinterpret_cast<::Matrix_proto*>(p);
  }
  return _impl_.pomatrix_;
}
inline ::Matrix_proto* GameObject_proto::mutable_pomatrix() {
  ::Matrix_proto* _msg = _internal_mutable_pomatrix();
  // @@protoc_insertion_point(field_mutable:GameObject_proto.poMatrix)
  return _msg;
}
inline void GameObject_proto::set_allocated_pomatrix(::Matrix_proto* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pomatrix_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.pomatrix_ = reinterpret_cast<::Matrix_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameObject_proto.poMatrix)
}

// optional .Vect_proto poVect = 2;
inline bool GameObject_proto::has_povect() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.povect_ != nullptr);
  return value;
}
inline const ::Vect_proto& GameObject_proto::_internal_povect() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::Vect_proto* p = _impl_.povect_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vect_proto&>(::_Vect_proto_default_instance_);
}
inline const ::Vect_proto& GameObject_proto::povect() const {
  // @@protoc_insertion_point(field_get:GameObject_proto.poVect)
  return _internal_povect();
}
inline void GameObject_proto::unsafe_arena_set_allocated_povect(::Vect_proto* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.povect_);
  }
  _impl_.povect_ = reinterpret_cast<::Vect_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameObject_proto.poVect)
}
inline ::Vect_proto* GameObject_proto::release_povect() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Vect_proto* released = _impl_.povect_;
  _impl_.povect_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Vect_proto* GameObject_proto::unsafe_arena_release_povect() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:GameObject_proto.poVect)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Vect_proto* temp = _impl_.povect_;
  _impl_.povect_ = nullptr;
  return temp;
}
inline ::Vect_proto* GameObject_proto::_internal_mutable_povect() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.povect_ == nullptr) {
    auto* p = CreateMaybeMessage<::Vect_proto>(GetArenaForAllocation());
    _impl_.povect_ = reinterpret_cast<::Vect_proto*>(p);
  }
  return _impl_.povect_;
}
inline ::Vect_proto* GameObject_proto::mutable_povect() {
  ::Vect_proto* _msg = _internal_mutable_povect();
  // @@protoc_insertion_point(field_mutable:GameObject_proto.poVect)
  return _msg;
}
inline void GameObject_proto::set_allocated_povect(::Vect_proto* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.povect_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.povect_ = reinterpret_cast<::Vect_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameObject_proto.poVect)
}

// optional float x = 3;
inline bool GameObject_proto::has_x() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void GameObject_proto::clear_x() {
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float GameObject_proto::x() const {
  // @@protoc_insertion_point(field_get:GameObject_proto.x)
  return _internal_x();
}
inline void GameObject_proto::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:GameObject_proto.x)
}
inline float GameObject_proto::_internal_x() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.x_;
}
inline void GameObject_proto::_internal_set_x(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.x_ = value;
}

// optional sint32 i = 4;
inline bool GameObject_proto::has_i() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void GameObject_proto::clear_i() {
  _impl_.i_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t GameObject_proto::i() const {
  // @@protoc_insertion_point(field_get:GameObject_proto.i)
  return _internal_i();
}
inline void GameObject_proto::set_i(::int32_t value) {
  _internal_set_i(value);
  // @@protoc_insertion_point(field_set:GameObject_proto.i)
}
inline ::int32_t GameObject_proto::_internal_i() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.i_;
}
inline void GameObject_proto::_internal_set_i(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.i_ = value;
}

// optional .Vect_proto vA = 5;
inline bool GameObject_proto::has_va() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.va_ != nullptr);
  return value;
}
inline const ::Vect_proto& GameObject_proto::_internal_va() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::Vect_proto* p = _impl_.va_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vect_proto&>(::_Vect_proto_default_instance_);
}
inline const ::Vect_proto& GameObject_proto::va() const {
  // @@protoc_insertion_point(field_get:GameObject_proto.vA)
  return _internal_va();
}
inline void GameObject_proto::unsafe_arena_set_allocated_va(::Vect_proto* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.va_);
  }
  _impl_.va_ = reinterpret_cast<::Vect_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameObject_proto.vA)
}
inline ::Vect_proto* GameObject_proto::release_va() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::Vect_proto* released = _impl_.va_;
  _impl_.va_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Vect_proto* GameObject_proto::unsafe_arena_release_va() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:GameObject_proto.vA)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::Vect_proto* temp = _impl_.va_;
  _impl_.va_ = nullptr;
  return temp;
}
inline ::Vect_proto* GameObject_proto::_internal_mutable_va() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.va_ == nullptr) {
    auto* p = CreateMaybeMessage<::Vect_proto>(GetArenaForAllocation());
    _impl_.va_ = reinterpret_cast<::Vect_proto*>(p);
  }
  return _impl_.va_;
}
inline ::Vect_proto* GameObject_proto::mutable_va() {
  ::Vect_proto* _msg = _internal_mutable_va();
  // @@protoc_insertion_point(field_mutable:GameObject_proto.vA)
  return _msg;
}
inline void GameObject_proto::set_allocated_va(::Vect_proto* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.va_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.va_ = reinterpret_cast<::Vect_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameObject_proto.vA)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_GameObject_2eproto_2epb_2eh
