// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Material.proto

#include "Material.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
        template <typename>
PROTOBUF_CONSTEXPR Material_proto::Material_proto(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.a_)*/ 0,
      /*decltype(_impl_.b_)*/ 0,
      /*decltype(_impl_.c_)*/ 0,
      /*decltype(_impl_.x_)*/ 0,
    } {}
struct Material_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Material_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Material_protoDefaultTypeInternal() {}
  union {
    Material_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Material_protoDefaultTypeInternal _Material_proto_default_instance_;
bool Material_proto_Color_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    Material_proto_Color_strings[4] = {};

static const char Material_proto_Color_names[] = {
    "Blue"
    "Red"
    "White"
    "Yellow"
};

static const ::google::protobuf::internal::EnumEntry Material_proto_Color_entries[] =
    {
        {{&Material_proto_Color_names[0], 4}, 0},
        {{&Material_proto_Color_names[4], 3}, 2},
        {{&Material_proto_Color_names[7], 5}, 1},
        {{&Material_proto_Color_names[12], 6}, 3},
};

static const int Material_proto_Color_entries_by_number[] = {
    0,  // 0 -> Blue
    2,  // 1 -> White
    1,  // 2 -> Red
    3,  // 3 -> Yellow
};

const std::string& Material_proto_Color_Name(Material_proto_Color value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          Material_proto_Color_entries, Material_proto_Color_entries_by_number,
          4, Material_proto_Color_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      Material_proto_Color_entries, Material_proto_Color_entries_by_number, 4,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : Material_proto_Color_strings[idx].get();
}

bool Material_proto_Color_Parse(absl::string_view name, Material_proto_Color* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      Material_proto_Color_entries, 4, name, &int_value);
  if (success) {
    *value = static_cast<Material_proto_Color>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr Material_proto_Color Material_proto::Blue;
constexpr Material_proto_Color Material_proto::White;
constexpr Material_proto_Color Material_proto::Red;
constexpr Material_proto_Color Material_proto::Yellow;
constexpr Material_proto_Color Material_proto::Color_MIN;
constexpr Material_proto_Color Material_proto::Color_MAX;
constexpr int Material_proto::Color_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class Material_proto::_Internal {
 public:
  using HasBits = decltype(std::declval<Material_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Material_proto, _impl_._has_bits_);
  static void set_has_a(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_b(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_c(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_x(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

Material_proto::Material_proto(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Material_proto)
}
Material_proto::Material_proto(const Material_proto& from)
    : ::google::protobuf::MessageLite(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Material_proto)
}
inline void Material_proto::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.a_){0},
      decltype(_impl_.b_){0},
      decltype(_impl_.c_){0},
      decltype(_impl_.x_){0},
  };
}
Material_proto::~Material_proto() {
  // @@protoc_insertion_point(destructor:Material_proto)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void Material_proto::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void Material_proto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void Material_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:Material_proto)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&_impl_.a_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.x_) -
        reinterpret_cast<char*>(&_impl_.a_)) + sizeof(_impl_.x_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* Material_proto::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> Material_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Material_proto, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Material_proto_default_instance_._instance,
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
  }, {{
    // optional sint32 x = 4;
    {::_pbi::TcParser::FastZ32S1,
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(Material_proto, _impl_.x_)}},
    // optional .Material_proto.Color a = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Material_proto, _impl_.a_)}},
    // optional .Material_proto.Color b = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(Material_proto, _impl_.b_)}},
    // optional .Material_proto.Color c = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(Material_proto, _impl_.c_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .Material_proto.Color a = 1;
    {PROTOBUF_FIELD_OFFSET(Material_proto, _impl_.a_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional .Material_proto.Color b = 2;
    {PROTOBUF_FIELD_OFFSET(Material_proto, _impl_.b_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional .Material_proto.Color c = 3;
    {PROTOBUF_FIELD_OFFSET(Material_proto, _impl_.c_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional sint32 x = 4;
    {PROTOBUF_FIELD_OFFSET(Material_proto, _impl_.x_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kSInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Material_proto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Material_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .Material_proto.Color a = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_a(), target);
  }

  // optional .Material_proto.Color b = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_b(), target);
  }

  // optional .Material_proto.Color c = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this->_internal_c(), target);
  }

  // optional sint32 x = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        4, this->_internal_x(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Material_proto)
  return target;
}

::size_t Material_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Material_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional .Material_proto.Color a = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_a());
    }

    // optional .Material_proto.Color b = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_b());
    }

    // optional .Material_proto.Color c = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_c());
    }

    // optional sint32 x = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
          this->_internal_x());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Material_proto::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Material_proto*>(
      &from));
}

void Material_proto::MergeFrom(const Material_proto& from) {
  Material_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:Material_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.a_ = from._impl_.a_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.b_ = from._impl_.b_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.c_ = from._impl_.c_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.x_ = from._impl_.x_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Material_proto::CopyFrom(const Material_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Material_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Material_proto::IsInitialized() const {
  return true;
}

void Material_proto::InternalSwap(Material_proto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Material_proto, _impl_.x_)
      + sizeof(Material_proto::_impl_.x_)
      - PROTOBUF_FIELD_OFFSET(Material_proto, _impl_.a_)>(
          reinterpret_cast<char*>(&_impl_.a_),
          reinterpret_cast<char*>(&other->_impl_.a_));
}

std::string Material_proto::GetTypeName() const {
  return "Material_proto";
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
