// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Texture.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Texture_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Texture_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Texture_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Texture_2eproto {
  static const ::uint32_t offsets[];
};
class Texture_proto;
struct Texture_protoDefaultTypeInternal;
extern Texture_protoDefaultTypeInternal _Texture_proto_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Texture_proto final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Texture_proto) */ {
 public:
  inline Texture_proto() : Texture_proto(nullptr) {}
  ~Texture_proto() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Texture_proto(::google::protobuf::internal::ConstantInitialized);

  Texture_proto(const Texture_proto& from);
  Texture_proto(Texture_proto&& from) noexcept
    : Texture_proto() {
    *this = ::std::move(from);
  }

  inline Texture_proto& operator=(const Texture_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline Texture_proto& operator=(Texture_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Texture_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const Texture_proto* internal_default_instance() {
    return reinterpret_cast<const Texture_proto*>(
               &_Texture_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Texture_proto& a, Texture_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(Texture_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Texture_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Texture_proto* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Texture_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)  final;
  void CopyFrom(const Texture_proto& from);
  void MergeFrom(const Texture_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Texture_proto* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Texture_proto";
  }
  protected:
  explicit Texture_proto(::google::protobuf::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPoDataFieldNumber = 1,
    kDataSizeFieldNumber = 2,
  };
  // optional bytes poData = 1;
  bool has_podata() const;
  void clear_podata() ;
  const std::string& podata() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_podata(Arg_&& arg, Args_... args);
  std::string* mutable_podata();
  PROTOBUF_NODISCARD std::string* release_podata();
  void set_allocated_podata(std::string* ptr);

  private:
  const std::string& _internal_podata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_podata(
      const std::string& value);
  std::string* _internal_mutable_podata();

  public:
  // optional uint32 DataSize = 2;
  bool has_datasize() const;
  void clear_datasize() ;
  ::uint32_t datasize() const;
  void set_datasize(::uint32_t value);

  private:
  ::uint32_t _internal_datasize() const;
  void _internal_set_datasize(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Texture_proto)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr podata_;
    ::uint32_t datasize_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Texture_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Texture_proto

// optional bytes poData = 1;
inline bool Texture_proto::has_podata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Texture_proto::clear_podata() {
  _impl_.podata_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Texture_proto::podata() const {
  // @@protoc_insertion_point(field_get:Texture_proto.poData)
  return _internal_podata();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Texture_proto::set_podata(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.podata_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Texture_proto.poData)
}
inline std::string* Texture_proto::mutable_podata() {
  std::string* _s = _internal_mutable_podata();
  // @@protoc_insertion_point(field_mutable:Texture_proto.poData)
  return _s;
}
inline const std::string& Texture_proto::_internal_podata() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.podata_.Get();
}
inline void Texture_proto::_internal_set_podata(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.podata_.Set(value, GetArenaForAllocation());
}
inline std::string* Texture_proto::_internal_mutable_podata() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.podata_.Mutable( GetArenaForAllocation());
}
inline std::string* Texture_proto::release_podata() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Texture_proto.poData)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.podata_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.podata_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Texture_proto::set_allocated_podata(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.podata_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.podata_.IsDefault()) {
          _impl_.podata_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Texture_proto.poData)
}

// optional uint32 DataSize = 2;
inline bool Texture_proto::has_datasize() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Texture_proto::clear_datasize() {
  _impl_.datasize_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t Texture_proto::datasize() const {
  // @@protoc_insertion_point(field_get:Texture_proto.DataSize)
  return _internal_datasize();
}
inline void Texture_proto::set_datasize(::uint32_t value) {
  _internal_set_datasize(value);
  // @@protoc_insertion_point(field_set:Texture_proto.DataSize)
}
inline ::uint32_t Texture_proto::_internal_datasize() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.datasize_;
}
inline void Texture_proto::_internal_set_datasize(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.datasize_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Texture_2eproto_2epb_2eh
